### ISSUE TITLE
Pretrained models to reproduce paper's results

### ISSUE THREAD

**Issue by NahyukLEE** [Jiaxin-Lu/Jigsaw#3]
Thank you for your great work!

Do you have any plan to share your pretrained model on **"artifact"** subset that can reproduce results in paper?
If you can, I will very appreciate with that.

Thanks.

**Comment by Jiaxin-Lu** [comment]
The result of "artifact" subset is based on the "jigsaw_multi_4x4_128_512_250e_cosine_everyday" model we shared, which is trained only on the everyday subset. There is no further training or finetuning to the model.
