### ISSUE TITLE
Coordinate system anchoring and error calculation in evaluation

### ISSUE THREAD

**Issue by adeela-islam** [Jiaxin-Lu/Jigsaw#5]
Thank you for the work. I've been reviewing the codebase, specifically looking for the implementation details related to anchoring the coordinate system to the canonical one of the largest pieces in the experiment. Additionally, I'm interested in understanding how errors are calculated on other pieces during the evaluation process.

Could you kindly guide me on where in the codebase these functionalities are implemented? Any pointers or specific files related to these aspects would be greatly appreciated.

Thank you.

**Comment by Jiaxin-Lu** [comment]
After last update, the global transformation estimation is in [utils/estimate_transform.py](https://github.com/Jiaxin-Lu/Jigsaw/blob/main/utils/estimate_transform.py). There is a function for aligning pieces to a given pivot [align_to_pivot](https://github.com/Jiaxin-Lu/Jigsaw/blob/main/utils/estimate_transform.py#L145). 
For calculating the metrics, a calc_metric function is in the [matching_base_model](https://github.com/Jiaxin-Lu/Jigsaw/blob/main/model/modules/matching_base_model.py#L104) where you can calculate the metrics based on gt and estimated transformations.

**Comment by pmorerio** [comment]
Hi and thank you very much for the nice work and for sharing the code.
According to the paper (Section 3.4) 

> we anchor the coordinate system to the canonical one of the largest pieces in our experiment and measure the errors over all other pieces of the fractured object

However, from the metrics detailed in your comment above I could see no such a thing as the exclusion of the largest piece from the calculation of the metric. From my understanding of the code, the error is calculated over all the pieces.

Hope you can clarify this!

**Comment by Nes-tle** [comment]
Since the largest piece is anchored, it will contribute 0 error in rotation and translation, which means the accumulated error only comes from other pieces.

**Comment by pmorerio** [comment]
@Nes-tle exactly. 
However by averaging over _all pieces_, zero-error piece is actually contributing to the metrics. 
This affect accuracy a lot, especially in puzzle with few pieces. In the extreme case of a 2-piece puzzle, base accuracy will be 50%.
Also, RMSD error is affected a lot, since the zero error piece is accounted for in the average.

**Comment by pmorerio** [comment]
@Jiaxin-Lu @Nes-tle I want to clarify that I am not saying that the evaluation is unfair.
However, what is written in the paper my be misleading, since one may think that metrics are calculated by excluding the largest pieace.

**Comment by Nes-tle** [comment]
@pmorerio Yes. We are taking the largest piece into account. As you can see, the current implementation of global alignment will bring some benefits in PA, but lose optimality in rotation and translation averaging. This project is still far from solving the assembly problem, and I would suggest taking PA as a minor standard.

**Comment by pmorerio** [comment]
Well, @Nes-tle @Jiaxin-Lu  thank you very much for the fruitful discussion, that clarifies everything :smiley:
