### ISSUE TITLE
How to visualize？

### ISSUE THREAD

**Issue by cxyLenbai** [Jiaxin-Lu/Jigsaw#6]
Hello, I currently need to visualize the splicing results, but I have not found the visual code or the corresponding transformation matrix, what should I do?

**Comment by Jiaxin-Lu** [comment]
We used open3D for visualization but it is ran locally due to its incompatibility with the current environment's open3D version. 

To implement your own visualization code, you shall use the saved `stats` file. Begin by transferring the pieces using the inverse of the ground truth transformation (here, the transfer of 'T' should take first, further details can be found in the dataset code). Then you can transfer them utilizing the predicted result, a standard transformation procedure.

**Comment by cxyLenbai** [comment]
Hi, I took a look at the stats file. But the contents of the inside I can not understand, the file starts with a series of T transformation matrix, and then becomes T matrix and R matrix alternate.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jiaxin-Lu/Jigsaw"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 凌晨0:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jiaxin-Lu/Jigsaw] How to visualize？ (Issue #6)





 
We used open3D for visualization but it is ran locally due to its incompatibility with the current environment's open3D version.
 
To implement your own visualization code, you shall use the saved stats file. Begin by transferring the pieces using the inverse of the ground truth transformation (here, the transfer of 'T' should take first, further details can be found in the dataset code). Then you can transfer them utilizing the predicted result, a standard transformation procedure.

**Comment by Jiaxin-Lu** [comment]
You can get a batch of ground truth transformations from `stats['datas'][i]['gt_trans']` and `stats['datas'][i]['gt_rot']` (where `i` is the batch number, and you can get the index of the data in current batch by looking at `stats['datas'][i]['data_id']`). You can also get a batch of predicted transformations from `stats['preds'][i]['trans']` and `stats['preds'][i]['rot']` (the order `i` is aligned with the ground truth and so does the index of the data). These information would be sufficient to recover the result.

**Comment by cxyLenbai** [comment]
Hello, recently I trained my own data set on your 3D fractured object splicing model, but I found that the training results are not convergent. Is there any suggestion or method? PS: In the original training configuration, I only changed the batch_size from 4 to 2, and nothing else changed.

**Comment by Jiaxin-Lu** [comment]
Could you provide any information on the dataset size, object scale, and how the fractured surface might look like? You may also check out [our training log](https://api.wandb.ai/links/assembly/u5s0xykd) we provided and compare the performance.
